---
title: "dm.Rmd"
author: "Brandon Leff"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section to Load in Data

```{r}
#nfl <- read.csv("~/MATH456/nflplaybyplay.csv")
#nfl <- read.csv("/Users/brandonleff/Desktop/math456/nflplaybyplay.csv")
nfl <- read.csv("/home/taudin/MiscFiles/Spring20/MATH456/NFLData/nflplaybyplay.csv")
```

```{r}
library(dplyr)
```

```{r var-names-lower}
names(nfl) <- tolower(names(nfl))
```

```{r manual-var-select}
play_predict <- nfl %>% select(date,gameid,drive,qtr,down,timesecs,sideoffield,yrdln,ydstogo,firstdown,posteam,defensiveteam,playattempted,yards.gained,touchdown,playtype,passattempt,passoutcome,passlength,airyards,yardsaftercatch,qbhit,passlocation,interceptionthrown,rushattempt,runlocation,rungap,fumble,sack,challenge.replay,chalreplayresult,penalizedteam,penalty.yards,posteamscore,defteamscore,hometeam,awayteam,scorediff,no_score_prob,touchdown_prob)
```

# Adding Day of the week Variable

```{r day-of-week}
play_predict$day <- weekdays(as.Date(play_predict$date))
```

# Changing team labels for rams and jaguars

```{r as-character}
play_predict$posteam <- as.character(play_predict$posteam)
play_predict$defensiveteam <- as.character(play_predict$defensiveteam)
play_predict$penalizedteam <- as.character(play_predict$penalizedteam)
play_predict$hometeam <- as.character(play_predict$hometeam)
play_predict$awayteam <- as.character(play_predict$awayteam)
```

```{r jaguars-rams}
play_predict$posteam[play_predict$posteam == "STL"] <- "LA"
play_predict$posteam[play_predict$posteam == "JAC"] <- "JAX"
play_predict$defensiveteam[play_predict$defensiveteam == "STL"] <- "LA"
play_predict$defensiveteam[play_predict$defensiveteam == "JAC"] <- "JAX"
play_predict$penalizedteam[play_predict$penalizedteam == "STL"] <- "LA"
play_predict$penalizedteam[play_predict$penalizedteam == "JAC"] <- "JAX"
play_predict$hometeam[play_predict$hometeam == "STL"] <- "LA"
play_predict$hometeam[play_predict$hometeam == "JAC"] <- "JAX"
play_predict$awayteam[play_predict$awayteam == "STL"] <- "LA"
play_predict$awayteam[play_predict$awayteam == "JAC"] <- "JAX"
```

```{r}
table(play_predict$hometeam)
```

# Make the dataset plays where only a pass, run, sack, spike, punt happened

```{r only-pass-run-sack-spike-punt}
dope_plays <- c("Pass", "Run", "Sack", "Spike", "Punt")
play_predict <- play_predict %>% filter(playtype %in% dope_plays)
play_predict$playtype <- droplevels(play_predict$playtype)
```

```{r drop-levels-50-yard-line}
play_predict$sideoffield <- droplevels(play_predict$sideoffield)
```

```{r drop-play-attempted-var}
play_predict <- play_predict %>% select(-c(playattempted))
```

```{r drop-play-pass-20}
table(play_predict$penalizedteam)
```


## Create a Clean Dataset (Everyone)

```{r}
#saveRDS(nfl2, file="~/MATH456/nfl.rds")
```

